image: registry.gitlab.com/pheix-pool/docker-core-perl6:latest

before_script:
  - raku --version
  - zef update
  - zef --debug --depsonly install git://github.com/ugexe/zef.git
test:
  script:
    - zef --deps-only install .
    - prove6 -Ilib ./t/
    - zef --verbose install .
    - RAKULIB=./lib trove-cli -c -l --s='1' --f=`pwd`/x/trove-configs/test.conf.yaml --v='0.0.1' --g=`pwd` --p=yq -d
    - RAKULIB=./lib trove-cli -c --f=`pwd`/x/trove-configs/test.conf.yaml.explore --p=yq -d
  only:
    - main
    - explore-feature
