target: Trove test suite
staticlines: 10
stages:
  - test: raku ./t/01.t
  - test: raku ./t/02.t
    substages:
      - test: ls -la .
      - test: ls -la /etc
    environment:
      - 'export TROVE_ENV_VAR=magic-trove-env-value'
    cleanup:
      - 'unset TROVE_ENV_VAR'
  - test: raku ./t/03.t
